### PR TITLE
feat: support both single- and double- quoted strings

### PR DESCRIPTION
**Pull request by llllvvuu**
These are supported by `lua-language-server`.

### CODE REVIEW

**Comment by amaanq** [comment]
thanks - can we generate with master? I can force push or you can - up to you, you may install it with `cargo install --git https://github.com/tree-sitter/tree-sitter` if you have rust installed

**Comment by llllvvuu** [comment]
Yup, just did (`46af277`)

**Comment by amaanq** [comment]
formatting :sweat_smile: `npm run lint --fix` should fix it

**Comment by llllvvuu** [comment]
fixed

**Comment by amaanq** [comment]
awesome, just rebase your other pr and regenerate

**Comment by llllvvuu** [comment]
> awesome, just rebase your other pr and regenerate

just did

**Pull request merged**
