### PR TITLE
fix: correctly recognize multiple inheritance for `@class`

### PR DESCRIPTION
**Pull request by wookayin**
Problem: Inheritance from multiple parent types are not correctly
recognized, only the first parent class was parsed as identifier.

Solution: Use commaSep to recognize multiple parent types.

### CODE REVIEW

**Comment by wookayin** [comment]
Preview: (Before / After)

image

**Comment by wookayin** [comment]
I see a lot of style changes in src/tree_sitter/parser.h, this is probably due to the different tree-sitter CLI version used. I used 0.20.8; please let me know if this is causing any problem/conflicts.

**Comment by wookayin** [comment]
@amaanq kindly bumping this up.

**Comment by amaanq** [comment]
Thank you for the PR! And I'm sorry about being MIA

For future tree-sitter parser related PRs, make sure your cli is built from master, there's slight changes in the generation output

**Pull request merged**
